language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: MKLLWsWkSmKwqLAErbOEcsg2u/Bq9nOsuuuUjd3nuhZ5W0MqnYUi5yyIBQ4cAMmNcXyIT2LOI278+iTx9HoZLzS8QJhXeVfiRKuhsLdvlys9g/x8tWdpqk0EjIXHTTfHs+xDP/mf1/Dfzno+58phxqd7LhinflJ9CqQ464RJ8vxDMupzvYU2HxnrfXFWETDzciJWDTVhAkqxc2jpavpz+4HuPr2NfMxWwlJtpgyTKlg+IosUjtmWAgxGdPTEE+BZpc6XPPR3aQptTiPsmppOS4WS3RcLzFCe+rketYykbRK2kCU0diQSmD6q5szUMI2BRxxcZK72GXvAIoEPts73KhbqzxAQNWCG9ZBdzvE7EwZ5b2mgMx2mi024C4WTRtHsGXd/vnz4vljZ9ftf2JBRWbRmxK6XGwvMjIGbV0gS4PgCxf+DHebTVGdusvB0bKxJKxIC6VMPMGy9RkoPWIfow+xTseN+nNDEtC45f9g9uIRSlmsogCy74++CUYjmEfkOENzCSbLE9UsJ0FuF8zqK2l8cnsYZKMzjllFAgcTXULarEv/9zy4gYFa31sIBQ0myIpuTZolOy1GK6WI0feHRVPbyYp1ttS6gN6PQZNZmx4svPvnehUc1QfHDS8QUGiHLzhlMV2ZMyemNTRYaf7hZMOKGXTpeCDCyF5bIHvjg2lI=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: fvR+o7G0TCdY4xEx1CgGx7gsEkfcp91kHmxdIYzdO9jlxbQmlbvKIP2Mr0MgeXPOHN0Am7gj5hW8/h5HNi+V69nJnzEEWYy/zK1egWheYR7t6JtdBfu6xX2QwoKSWGfAFPNOc+T4pQKHSMT+HnzHRbb4Wc9ROXmSZo3b5VbZAL8mG0ejBRv9iR8hEFkEtS0YJK/m3uGOsdTUu0+tyvG8G4Q4Zd+CHDwBO5Bz22MWLwhHJL5EBzEcsGF/7Hqreg6udIUgl8rLDRAP2UetrvQeH8EohcnmrsIjtPFIW+8w2AP9K5hrP7MSh3WQ+DKXMeOLJ0VRG/jty7W3fKk1QIEjpANhFDtfYN41xygkKoZMRabxanpE+FdxS8asGe3Vr0W50oq41cnx2Q6vGUV8ZTBfmI4el4DNAoYVJMelWwrfuN2fNW2mv4xR33NFnNJmoBP16RjnTXqWe7nJUdNPVkf6JvYfd9gUf8VhyPh9Rh0VEcdtk8cZSeYLLGIjVOHcxTurltpkfz5G225TWznkg60OvE/r1MUjplIC1bDxwGmUK27zOtRMPkJx6Lzf/yareyZuBG1glrF9fKpMWsM4xIX/MFkRDZvkvc3vA8j7IqrZZZ+zIYRpcecvWxHJMU+Ljh1mzbz5Qyywnk/XhRU/IhlvwzC4C3M21cn8tk0da40m8Ak=
sudo: false
